spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/taskflow_db
        username: postgres
        password: rootroot
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
port: 8080
